name: Build and update dist folder

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
    - run: npm ci
    - run: npm run type-check
    - run: npm run build-prod
    - run: npm run test --if-present
    - name: Update dist folder
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
              dist/*.js
              dist/*.map
              dist/*.txt
          commit-msg: Auto-update distribution
          github-token: ${{ secrets.GITHUB_TOKEN }}
