name: "Unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all_tests:
    uses: mlee03/pyFV3/.github/workflows/translate.yml@reusing_workflows
    with:
      ndsl_hash: ${{GITHUB_SHA}}
