name: "SHiELD Translate tests"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  shield_translate_tests:
    uses: NOAA-GFDL/pySHiELD/.github/workflows/translate.yaml@develop
    with:
      ndsl_trigger:  true
