name: "Unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/miniforge:mpich
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: Install Python packages
          run: |
            bash 
            echo "y" | conda create --name=test python=3.11.7 
            conda init            
            conda activate test
            pip3 install .[test]
        - name: Run serial-cpu tests
          run: coverage run --rcfile=setup.cfg -m pytest -x tests
        - name: Run parallel-cpu tests
          run: mpirun -np 6 coverage run --rcfile=setup.cfg -m mpi4py -m pytest -x tests/mpi
        - name: output coverage
          run: |
            coverage combine
            coverage report
