name: "Unit tests"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8.12, 3.11.7]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3.5.2
          with:
            submodules: 'recursive'
        - name: Setup Python
          uses: actions/setup-python@v4.6.0
          with:
            python-version: ${{ matrix.python }}
        - name: Install OpenMPI & Boost for gt4py
          run: |
            sudo apt-get install libopenmpi-dev libboost1.74-dev
        - name: Install Python packages
          run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install .[test]
        - name: Run serial-cpu tests
          run: |
            pytest -x tests
        - name: Run parallel-cpu tests
          run: |
            mpirun -np 6 --oversubscribe pytest -x tests/mpi
